// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfA1qcunyRCCLmtzv49FKbngKiBtCD4I',
    appId: '1:33898445131:web:1ea53f7954a6492d1850ce',
    messagingSenderId: '33898445131',
    projectId: 'chatapp-e10ee',
    authDomain: 'chatapp-e10ee.firebaseapp.com',
    storageBucket: 'chatapp-e10ee.appspot.com',
    measurementId: 'G-064WN1Y24K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDibF_XRT_9qbA87DlAnffDg-Y-PD4WWKs',
    appId: '1:33898445131:android:fe20f9165a4518c11850ce',
    messagingSenderId: '33898445131',
    projectId: 'chatapp-e10ee',
    storageBucket: 'chatapp-e10ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IpBzn1F574waEKNdb7aefFbb28rJRyM',
    appId: '1:33898445131:ios:dc24a6c98c1b0c221850ce',
    messagingSenderId: '33898445131',
    projectId: 'chatapp-e10ee',
    storageBucket: 'chatapp-e10ee.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
